'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOCATION
    Public Property ID As Integer
    Public Property COUNTRY_NAME As String
    Public Property BRANCH_NAME As String
    Public Property LOCATION_CODE As Nullable(Of Integer)

    Public Overridable Property DEMANDs As ICollection(Of DEMAND) = New HashSet(Of DEMAND)

End Class
