'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SKU
    Public Property ID As Integer
    Public Property NAME As String
    Public Property SKU_TYPE_LINK_ID As Nullable(Of Integer)

    Public Overridable Property DEMANDs As ICollection(Of DEMAND) = New HashSet(Of DEMAND)
    Public Overridable Property SKU_TYPE As SKU_TYPE

End Class
